"""Generate the bounded OSC 66 Unicode tables (no runtime dependency).

Usage: python3 gen-unicode16.py /path/to/downloaded-unicode16 /path/to/mosh
Inputs from https://www.unicode.org/Public/16.0.0/ucd/ and
https://www.unicode.org/Public/emoji/16.0/emoji-sequences.txt plus license.txt.
The generated data and test vectors carry the Unicode license in full.
"""
from array import array
from pathlib import Path
import sys

source, root = map(Path, sys.argv[1:])
props = array("H", [0]) * 0x110000
classes = "Other CR LF Control Extend ZWJ Regional_Indicator Prepend SpacingMark L V T LV LVT".split()


def records(name):
    for line in (source / name).read_text(encoding="utf-8").splitlines():
        line = line.split("#", 1)[0].strip()
        if line:
            yield [item.strip() for item in line.split(";")]


def span(value):
    ends = [int(x, 16) for x in value.split("..")]
    return range(ends[0], ends[-1] + 1)


for cp_range, name in records("GraphemeBreakProperty.txt"):
    for cp in span(cp_range):
        if not 0xAC00 <= cp <= 0xD7A3:  # algorithmic Hangul LV/LVT
            props[cp] |= classes.index(name)
for record in records("DerivedCoreProperties.txt"):
    if len(record) == 3 and record[1] == "InCB":
        for cp in span(record[0]):
            props[cp] |= {"Consonant": 512, "Extend": 1024, "Linker": 2048}[record[2]]
for cp_range, name in records("emoji-data.txt"):
    if name == "Extended_Pictographic":
        for cp in span(cp_range):
            props[cp] |= 16
for first, last in ((0x3400, 0x4DBF), (0x4E00, 0x9FFF), (0xF900, 0xFAFF), (0x20000, 0x2FFFD), (0x30000, 0x3FFFD), (0x1F1E6, 0x1F1FF)):
    for cp in range(first, last + 1):
        props[cp] |= 32
for cp_range, name in records("EastAsianWidth.txt"):
    for cp in span(cp_range):
        if name in ("W", "F"):
            props[cp] |= 32
        elif name == "A":
            props[cp] &= ~32
first = 0
for record in records("UnicodeData.txt"):
    cp, name, category = int(record[0], 16), record[1], record[2]
    if name.endswith(", First>"):
        first = cp
        continue
    for value in range(first if name.endswith(", Last>") else cp, cp + 1):
        if category[0] == "M" or category == "Cf":
            props[value] |= 64
        if category in ("Cc", "Cs"):
            props[value] |= 4096
for record in records("emoji-sequences.txt"):
    seq, kind = record[:2]
    codepoints = seq.split()
    if kind == "Basic_Emoji":
        for cp in span(codepoints[0]):
            props[cp] |= 256 if codepoints[-1] == "FE0F" else 32 | 128
    elif kind in ("RGI_Emoji_Modifier_Sequence", "RGI_Emoji_Tag_Sequence", "RGI_Emoji_Flag_Sequence"):
        props[int(codepoints[0], 16)] |= 32
        if kind == "RGI_Emoji_Flag_Sequence":
            props[int(codepoints[1], 16)] |= 32
        if kind == "RGI_Emoji_Modifier_Sequence":
            props[int(codepoints[-1], 16)] |= 64
for cp in range(0x110000):
    if 0xFDD0 <= cp <= 0xFDEF or cp & 0xFFFF in (0xFFFE, 0xFFFF):
        props[cp] |= 4096

notice = "/* Generated by gen-unicode16.py from Unicode 16.0.0 data.\n * Copyright 2024 Unicode, Inc.\n *\n" + "\n".join((" * " + x).rstrip() for x in (source / "LICENSE.txt").read_text().splitlines()) + "\n */\n"
output = [notice, "static const Range ranges[] = {\n"]
start = 0
for end in range(1, len(props) + 1):
    if end == len(props) or props[end] != props[start]:
        if props[start]:
            output.append(f"  {{ 0x{start:x}, 0x{end-1:x}, {props[start]} }},\n")
        start = end
output.append("};\n")
(root / "src/terminal/unicode16-data.h").write_text("".join(output))
tests = [notice, "static const wchar_t* break_tests[] = {\n"]
for line in (source / "GraphemeBreakTest.txt").read_text().splitlines():
    tokens = line.split("#", 1)[0].split()
    if not tokens:
        continue
    value = ""
    for token in tokens:
        if token == "÷":
            value += "\\U00110000"  # sentinel outside Unicode scalar range
        elif token != "×":
            value += f"\\U{int(token,16):08x}"
    # wchar_t literals forbid out-of-range Unicode escapes; use adjacent
    # string literals containing a noncharacter as the boundary sentinel.
    tests.append('  L"' + value.replace("\\U00110000", "\\ufdd0") + '",\n')
tests.append("};\n")
(root / "src/tests/unicode16-tests.h").write_text("".join(tests))
